#!/bin/bash

# Simpan data JSON ke dalam variabel (ganti dengan data JSON yang sebenarnya)
if [[ -f "./history.txt" ]]; then
    rm ./history.txt
    dunstctl history > ./history.txt 
else
    dunstctl history > ./history.txt
fi

json_data='./history.txt'

# Ekstrak isi dari summary, message, dan body menggunakan jq
message=$(echo "$json_data" | jq '.data[][] |= { body: .body.data, summary: .summary.data } | map(del(.message? | select(.type == "aasv" and .data)))' ./history.txt | sed 's/"//g;s/,//g;s/[{}]//g; s/[][]//g;s/<[^>]*>//g')

# Tampilkan hasil ekstraksi
echo "message: $message" > notification_history.txt
