#!/bin/bash

## Collect data
cache_dir="$HOME/.cache/eww/weather"
cache_weather_stat=${cache_dir}/weather-stat
cache_weather_degree=${cache_dir}/weather-degree
cache_weather_quote=${cache_dir}/weather-quote
cache_weather_hex=${cache_dir}/weather-hex
cache_weather_icon=${cache_dir}/weather-icon

## Weather data
KEY=d12714a4df8707506d6dd7688b3ccdfe
ID=1642911
UNIT='metric'	# Available options : 'metric' or 'imperial'

## Make cache dir
if [[ ! -d "$cache_dir" ]]; then
	mkdir -p ${cache_dir}
fi

## Get data
get_weather_data() {
	weather=$(curl -sf "http://api.openweathermap.org/data/2.5/weather?APPID="$KEY"&id="$ID"&units="$UNIT"")

	if [ ! -z "$weather" ]; then
		weather_temp=`echo "$weather" | jq ".main.temp" | cut -d "." -f 1`
		weather_icon_code=`echo "$weather" | jq -r ".weather[].icon" | head -1`
		weather_description=`echo "$weather" | jq -r ".weather[].description" | head -1 | sed -e "s/\b\(.\)/\u\1/g"`

		#Big long if statement of doom
		if [ "$weather_icon_code" == "50d"  ]; then
			weather_icon=" "
			weather_quote="Cuaca mengatakan hari ini berkabut \nJaga-jaga kamu tidak tersesat ke jalannya..."
			weather_hex="#84afdb"
		elif [ "$weather_icon_code" == "50n"  ]; then
			weather_icon=" "
			weather_quote="Cuaca mengatakan malam ini akan berkabut \nJangan pergi kemana-mana malam ini..."
			weather_hex="#84afdb"
		elif [ "$weather_icon_code" == "01d"  ]; then
			weather_icon=" "
			weather_quote="Wow cuaca yang cerah, Seru nih! \nJangan pergi tanpa berpikir ya..."
			weather_hex="#ffd86b"
		elif [ "$weather_icon_code" == "01n"  ]; then
			weather_icon=" "
			weather_quote="Malam hari yang indah \nKamu mungkin mau berjalan dengan tenang..."
			weather_hex="#fcdcf6"
		elif [ "$weather_icon_code" == "02d"  ]; then
			weather_icon=" "
			weather_quote="Ohh berawan, yang menenagkan \nKamu mungkin lebih baik membuat mie..."
			weather_hex="#adadff"
		elif [ "$weather_icon_code" == "02n"  ]; then
			weather_icon=" "
			weather_quote="Malam hari yang berawan ya \nBagaimana jika kita meminum segelas kopi?"
			weather_hex="#adadff"
		elif [ "$weather_icon_code" == "03d"  ]; then
			weather_icon=" "
			weather_quote="Wow awan yang indah \nMungkin lebih nikmat meneduh dibawah pohon..."
			weather_hex="#adadff"
		elif [ "$weather_icon_code" == "03n"  ]; then
			weather_icon=" "
			weather_quote="Awan yang berantakan \nNan indah di senja ini..."
			weather_hex="#adadff"
		elif [ "$weather_icon_code" == "04d"  ]; then
			weather_icon=" "
			weather_quote="Wow awan yang indah \nMungkin lebih nikmat meneduh dibawah pohon..."
			weather_hex="#adadff"
		elif [ "$weather_icon_code" == "04n"  ]; then
			weather_icon=" "
			weather_quote="Malam hari yang berawan ya \nBagaimana jika kita meminum segelas kopi?"
			weather_hex="#adadff"
		elif [ "$weather_icon_code" == "09d"  ]; then
			weather_icon=" "
			weather_quote="HUJAN!, hari yang mantap! \nMasak mie dan menonton youtube..."
			weather_hex="#6b95ff"
		elif [ "$weather_icon_code" == "09n"  ]; then
			weather_icon=" "
			weather_quote="Bakalan Hujan malem nih \nHarus cek jemuran nih..."
			weather_hex="#6b95ff"
		elif [ "$weather_icon_code" == "10d"  ]; then
			weather_icon=" "
			weather_quote="HUJAN!, hari yang mantap! \nMasak mie dan menonton youtube..."
			weather_hex="#6b95ff"
		elif [ "$weather_icon_code" == "10n"  ]; then
			weather_icon=" "
			weather_quote="Bakalan Hujan malem nih \nHarus cek jemuran nih..."
			weather_hex="#6b95ff"
		elif [ "$weather_icon_code" == "11d"  ]; then
			weather_icon=""
			weather_quote="Ada badai petir hari ini \nPastikan tidak meledak ke rumahmu..."
			weather_hex="#ffeb57"
		elif [ "$weather_icon_code" == "11n"  ]; then
			weather_icon=""
			weather_quote="Hmmm ada badai di malam hari \nPastikan ruangan anda hangat dan tutup jendela..."
			weather_hex="#ffeb57"
		elif [ "$weather_icon_code" == "13d"  ]; then
			weather_icon=" "
			weather_quote="It's gonna snow today \nYou'd better wear thick clothes and make a snowman as well!"
			weather_hex="#e3e6fc"
		elif [ "$weather_icon_code" == "13n"  ]; then
			weather_icon=" "
			weather_quote="It's gonna snow tonight \nMake sure you get up early tomorrow to see the sights..."
			weather_hex="#e3e6fc"
		elif [ "$weather_icon_code" == "40d"  ]; then
			weather_icon=" "
			weather_quote="Cuaca mengatakan hari ini berkabut \nJaga-jaga kamu tidak tersesat ke jalannya..."
			weather_hex="#84afdb"
		elif [ "$weather_icon_code" == "40n"  ]; then
			weather_icon=" "
			weather_quote="Cuaca mengatakan hari ini berkabut \nJaga-jaga kamu tidak tersesat ke jalannya..."
			weather_hex="#84afdb"
		else 
			weather_icon=" "
			weather_quote="Hmm bingung nih kepala \nPastikan kamu mempunyai hari yang indah!"
			weather_hex="#adadff"
		fi
		echo "$weather_icon" >  ${cache_weather_icon}
		echo "$weather_description" > ${cache_weather_stat}
		echo "$weather_temp""°C" > ${cache_weather_degree}
		echo -e "$weather_quote" > ${cache_weather_quote}
		echo "$weather_hex" > ${cache_weather_hex}
	else
		echo "Weather Unavailable" > ${cache_weather_stat}
		echo " " > ${cache_weather_icon}
		echo -e "Oh oke, gak ada cuaca ya? \nWalaupun tidak ada cuaca, hari ini akan menjadi yang terbaik!" > ${cache_weather_quote}
		echo "-" > ${cache_weather_degree}
		echo "#adadff" > ${tcache_weather_hex}
	fi
}

## Execute
	get_weather_data
if [[ "$1" == "--icon" ]]; then
	cat ${cache_weather_icon}
elif [[ "$1" == "--temp" ]]; then
	cat ${cache_weather_degree}
elif [[ "$1" == "--hex" ]]; then
	cat ${cache_weather_hex}
elif [[ "$1" == "--stat" ]]; then
	cat ${cache_weather_stat}
elif [[ "$1" == "--quote" ]]; then
	cat ${cache_weather_quote} | head -n1
elif [[ "$1" == "--quote2" ]]; then
	cat ${cache_weather_quote} | tail -n1
fi

