#!/bin/bash

wall=$(find $HOME/Pictures/wallpaper/Gif/ -type f -name "*.gif" | shuf -n 1)

swww kill
swww init

# swww img $wall

# You can also specify outputs:
# swww img -o wallpaper1 $wall

# Control how smoothly the transition will happen and/or it's frame rate
# For the step, smaller values = more smooth. Default = 20
# For the frame rate, default is 30.
swww img $wall --transition-type wipe --transition-angle 30 --transition-step 60 --transition-fps 60
