#!/bin/bash

wall=$(find $HOME/Pictures/wallpaper/ -type f  -name "*.png" | shuf -n 1)

# swww kill
swww init

# swww img $wall

# You can also specify outputs:
# swww img -o wallpaper1 $wall

# Control how smoothly the transition will happen and/or it's frame rate
# For the step, smaller values = more smooth. Default = 20
# For the frame rate, default is 30.
swww img $wall --outputs "eDP-1" --transition-bezier 1,.01,0,1.05 --transition-duration 2.1 --transition-type grow  --transition-step 255 --transition-pos top-right --transition-fps 60
swww img $wall --outputs "HDMI-A-2" --transition-bezier 1,.01,0,1.05 --transition-duration 2.1 --transition-type grow  --transition-step 255 --transition-pos top-right --transition-fps 60

# There are also many different transition effects:
# swww img <path/to/img> --transition-type center

# Note you may also control the above by setting up the SWWW_TRANSITION_FPS,
# SWWW_TRANSITION_STEP, and SWWW_TRANSITION environment variables.

# To see all options, run
rm -rf $HOME/.cache/swww/
